language: objective-c
osx_image: xcode8.3
xcode_project: BridgeAppSDK.xcodeproj
xcode_scheme: BridgeAppSDKSample
cache:
- bundler
before_install:
- bundle update
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
script:
- ./travis/build.sh
