language: objective-c
osx_image: xcode8.3
xcode_project: BridgeAppSDK.xcodeproj
xcode_scheme: BridgeAppSDKSample
cache:
- bundler
before_install:
- brew update
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
install:
- gem install fastlane -v 2.25.0
script:
- ./travis/build.sh
